services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile-qa
            args:
                - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
        container_name: disk-cleaner-qa
        ports:
            - '5174:80'
        restart: unless-stopped
