services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile-prod
            args:
                - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
        container_name: disk-cleaner-prod
        ports:
            - '80:80'
        restart: unless-stopped
